### ISSUE TITLE
0.1.6 introduces "Cannot find module middleware.mjs" error

### ISSUE THREAD

**Issue by dts** [wobsoriano/nuxt-iron-session#1]
Thanks for this super-helpful package!

After upgrading to 0.1.6, I get:

```
 ERROR  [worker reload] [worker init] Cannot find module '<path>/iron-session-oauth-test/.nuxt/dev/middleware.mjs' imported from <path>/iron-session-oauth-test/.nuxt/dev/index.mjs
```

Happy to post code if helpful, but I am currently back up and running by pinning to 0.1.4 - I'll investigate more when I have some time.

**Comment by wobsoriano** [comment]
Thanks! Fixed in 0.1.7.
